#include <iostream>
#include <string>
#include <stdlib.h>
#include "MeshTallyReader.hxx"

using namespace std;

const string VERSION = "0.2.6";

void PrintHelp(char *argv[])
{
    cout << argv[0] << endl <<
            "\n\t is an interface program between a mesh tally file" << endl <<
            "\t generated by MCNP and the visualization tool kit VTK." << endl;
    cout << "\nUsage : " << argv[0] << " InFileName [OutFileName]\n\n";

    exit(0);
}


int main(int argc, char* argv[])
{
    if(argc < 2 || argc > 3)
        PrintHelp(argv);

	{ // print version
		string v("-v"), version("--version");

		if(argv[1] == v || argv[1] == version)
		{
			cout << "\n=========================\n";
			cout << "   mt2vtk version " << VERSION << endl;
			cout << "=========================\n";
			exit(1);
		}
	}

    string fileName(argv[1]);
    MeshTallyReader readerObject(fileName);
    string outFileName(argv[argc-1]);
    readerObject.SetOutFileName(outFileName);
  //  readerObject.WriteVTK();

    string inp("-1");

    while(inp != "0" && inp != "q" )
    {
        cout << "Options\n====================\n";
        cout << "1 ... write all tallies and errors to vtk files\n";
        cout << "2 ... write selection of tallies and errors to vtk files\n";
        cout << "3 ... load further tally file\n";
        cout << "4 ... multiply tally by a given factor\n";
        cout << "5 ... perform operation between tallies/spectra\n";
        cout << "6 ... scale geometry by factor (e.g. MM to CM conversion)\n";
        cout << "7 ... list tally information\n";
        cout << "0 ... exit program\n";

        cout << "Option : ";

        cin >> inp;
        if(inp == "1")
        {
            readerObject.WriteAll();//VTK();
            // readerObject.WriteErrorVTK();
        }
        else if(inp == "2")
        {
            cout << endl << readerObject.NumberOfTallies() << " tallies available : ";
            readerObject.PrintTalliesAvailable();

            cout << "Enter list of tallies you want to export to vtk format: \n";
            char cList[256];
            cin.ignore();
            cin.getline(cList, 256);
            string strTallyList(cList);
            readerObject.WriteSelectedTallies(strTallyList);
        }
        else if(inp == "3")
        {
            string furtherFileName;
            cout << "\nName of file to read : ";
            cin >> furtherFileName;
            readerObject.ReadTallyFile(furtherFileName);
        }
        else if(inp == "4")
        {
            float factor(1.0);
            cout << "Enter Factor : ";
            cin >> factor;

            if(factor != 0)
                readerObject.Multiply(factor);
        }
        else if(inp == "5" && readerObject.NumberOfMeshes() > 1)
        {
            cout << "\nPerform calculation between tallies!\n";
            cout << "Operators available: + - * / \n";
            cout << "Syntax: Tally(.EnergyBin) OPERATOR Tally(.EnergyBin) \n\n";

            cout << "Available tallies : ";
            readerObject.PrintMeshesAvailable();

            cout << "\n---------------------------------\n" << endl;
            cout << "operation : ";

            string val1("0"), val2, op;

            cin >> val1 >> op >> val2;

            if(val1 != string("0"))
                readerObject.PerformOperation(val1, op, val2);
        }
        else if(inp == "6")
        {
            cout << "scaling factor : ";
            float scalingFactor;
            cin >> scalingFactor;
            readerObject.SetGeometryScalingFactor(scalingFactor);
        }
        else if(inp == "9")
        {
            readerObject.MakeIntegralList();
        }
        else if(inp == "7")
        {
            readerObject.PrintTallyInformation();
        }
    }

    return 0;
}
